// lib/data.ts
import { Prospect } from "./types";
import dayjs from "dayjs";

export const initialProspects: Prospect[] = [
  {
    id: "1",
    firstName: "John",
    lastName: "Doe",
    email: "john.doe@example.com",
    phone: "123-456-7890",
    company: "Acme Inc.",
    status: "New",
    dateAdded: dayjs().subtract(7, "day").toDate(),
  },
{
    id: "2",
    firstName: "Jane",
    lastName: "Smith",
    email: "jane.smith@example.com",
    phone: "987-654-3210",
    company: "XYZ Corp.",
    status: "Contacted",
    dateAdded: dayjs().subtract(5, "day").toDate(),
},
{
    id: "3",
    firstName: "Michael",
    lastName: "Johnson",
    email: "michael.johnson@example.com",
    phone: "555-123-4567",
    company: "ABC Ltd.",
    status: "Qualified",
    dateAdded: dayjs().subtract(3, "day").toDate(),
},
{
    id: "4",
    firstName: "Emily",
    lastName: "Brown",
    email: "emily.brown@example.com",
    phone: "111-222-3333",
    company: "123 Inc.",
    status: "Lost",
    dateAdded: dayjs().subtract(2, "day").toDate(),
},
{
    id: "5",
    firstName: "Daniel",
    lastName: "Taylor",
    email: "daniel.taylor@example.com",
    phone: "444-555-6666",
    company: "XYZ Corp.",
    status: "Won",
    dateAdded: dayjs().subtract(1, "day").toDate(),
},
{
    id: "6",
    firstName: "Olivia",
    lastName: "Martinez",
    email: "olivia.martinez@example.com",
    phone: "777-888-9999",
    company: "ABC Ltd.",
    status: "New",
    dateAdded: dayjs().toDate(),
},
{
    id: "7",
    firstName: "James",
    lastName: "Anderson",
    email: "james.anderson@example.com",
    phone: "222-333-4444",
    company: "123 Inc.",
    status: "Contacted",
    dateAdded: dayjs().toDate(),
},
{
    id: "8",
    firstName: "Sophia",
    lastName: "Garcia",
    email: "sophia.garcia@example.com",
    phone: "666-777-8888",
    company: "XYZ Corp.",
    status: "Qualified",
    dateAdded: dayjs().toDate(),
},
{
    id: "9",
    firstName: "Benjamin",
    lastName: "Wilson",
    email: "benjamin.wilson@example.com",
    phone: "999-000-1111",
    company: "ABC Ltd.",
    status: "Lost",
    dateAdded: dayjs().toDate(),
},
{
    id: "10",
    firstName: "Ava",
    lastName: "Lopez",
    email: "ava.lopez@example.com",
    phone: "333-444-5555",
    company: "123 Inc.",
    status: "Won",
    dateAdded: dayjs().toDate(),
}
  // Add more example prospects...
];
